IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[NAME_ADDRESS_LINES_TEST]') AND type in (N'U'))
ALTER TABLE [dbo].[NAME_ADDRESS_LINES_TEST] DROP CONSTRAINT IF EXISTS [DF_NAME_ADDRESS_LINES_TEST_DateTimeStamp]
GO

/****** Object:  Table [dbo].[NAME_ADDRESS_LINES_TEST]    Script Date: 10/26/2018 10:35:23 AM ******/
DROP TABLE IF EXISTS [dbo].[NAME_ADDRESS_LINES_TEST]
GO

/****** Object:  Table [dbo].[NAME_ADDRESS_LINES_TEST]    Script Date: 10/26/2018 10:35:23 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[NAME_ADDRESS_LINES_TEST]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[NAME_ADDRESS_LINES_TEST](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME_LINE1] [varchar](255) NULL,
	[NAME_LINE2] [varchar](255) NULL,
	[ADRS_LINE1] [varchar](255) NULL,
	[ADRS_LINE2] [varchar](255) NULL,
	[ADRS_LINE3] [varchar](255) NULL,
	[ADRS_LINE4] [varchar](255) NULL,
	[ADRS_LINE5] [varchar](255) NULL,
	[DateTimeStamp] [datetime] NOT NULL,
 CONSTRAINT [PK_NAME_ADDRESS_LINES_TEST] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF_NAME_ADDRESS_LINES_TEST_DateTimeStamp]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[NAME_ADDRESS_LINES_TEST] ADD  CONSTRAINT [DF_NAME_ADDRESS_LINES_TEST_DateTimeStamp]  DEFAULT (getdate()) FOR [DateTimeStamp]
END
GO


