IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[NAME_ADDRESS_LINES]') AND type in (N'U'))
ALTER TABLE [dbo].[NAME_ADDRESS_LINES] DROP CONSTRAINT IF EXISTS [DF_NAME_ADDRESS_LINES_DateTimeStamp]
GO

/****** Object:  Table [dbo].[NAME_ADDRESS_LINES]  Script Date: 10/19/2018 12:07:57 PM ******/
DROP TABLE IF EXISTS [dbo].[NAME_ADDRESS_LINES]
GO

/****** Object:  Table [dbo].[NAME_ADDRESS_LINES] c   Script Date: 10/19/2018 12:07:57 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[NAME_ADDRESS_LINES]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[NAME_ADDRESS_LINES] (
    [dimFolio_SK]   INT           NOT NULL,
    [dimRollYear]   INT           NOT NULL,
    [dimFolio_BK]   VARCHAR (255) NOT NULL,
    [NAME_LINE1]    VARCHAR (35)  NULL,
    [NAME_LINE2]    VARCHAR (35)  NULL,
    [ADRS_LINE1]    VARCHAR (35)  NULL,
    [ADRS_LINE2]    VARCHAR (35)  NULL,
    [ADRS_LINE3]    VARCHAR (35)  NULL,
    [ADRS_LINE4]    VARCHAR (35)  NULL,
    [ADRS_LINE5]    VARCHAR (35)  NULL,
    [DateTimeStamp] DATETIME      CONSTRAINT [DF_NAME_ADDRESS_LINES_DateTimeStamp] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_NAME_ADDRESS_LINES] PRIMARY KEY CLUSTERED ([dimFolio_SK] ASC, [dimRollYear] ASC)
)
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF_NAME_ADDRESS_LINES_DateTimeStamp]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[NAME_ADDRESS_LINES] ADD  CONSTRAINT [DF_NAME_ADDRESS_LINES_DateTimeStamp]  DEFAULT (getdate()) FOR [DateTimeStamp]
END
GO