CREATE OR ALTER PROCEDURE dbo.SP_TEST_FORMAT_ONE_LEGAL_DESCRIPTION
(
	@p_Type			VARCHAR(10) = 'SIMPLE'
)
AS
BEGIN	
	DECLARE	    @p_jurisdiction				VARCHAR(50),  
				@p_parcel					VARCHAR(50),  
				@p_parcel_length			INT,
				@p_lot						VARCHAR(50),  
				@p_lot_length				INT,
				@p_strata_lot				VARCHAR(50),  
				@p_strata_lot_length		INT,
				@p_block					VARCHAR(50),  
				@p_block_length				INT,
				@p_sub_block				VARCHAR(50),  
				@p_sub_block_length			INT,
				@p_plan						VARCHAR(50),  
				@p_plan_length				INT,
				@p_sub_lot					VARCHAR(50),  
				@p_sub_lot_length			INT,
				@p_part_1					VARCHAR(50),
				@p_part_2					VARCHAR(50),
				@p_part_3					VARCHAR(50),  
				@p_part_4					VARCHAR(50),  
				@p_part_length				INT,
				@p_district_lot				VARCHAR(50),  
				@p_district_lot_length		INT,
				@p_legal_subdivision		VARCHAR(50),  
				@p_legal_subdivision_length INT,
				@p_section					VARCHAR(50),  
				@p_section_length			INT,
				@p_township					VARCHAR(50),  
				@p_township_length			INT,
				@p_range					VARCHAR(50),  
				@p_range_length				INT,
				@p_meridian					VARCHAR(50),  
				@p_meridian_length			INT,
				@p_bcaao_group				VARCHAR(50),  
				@p_bcaao_group_length		INT,
				@p_land_district			VARCHAR(50),  
				@p_land_district_length		INT,
				@p_portion					VARCHAR(50),  
				@p_portion_length			INT,
				@p_except_plan				VARCHAR(50),  
				@p_except_plan_length		INT,
				@p_legal_text				VARCHAR(50),  
				@p_legal_text_length		INT,
				@p_air_space_parcel			VARCHAR(50),  
				@p_air_space_parcel_length	INT,
				@p_lease_licence_num		VARCHAR(50),  
				@p_lease_licence_num_length INT,
				@p_mf_num					VARCHAR(50),  
				@p_mf_num_length			INT,
				@p_mhr_number				VARCHAR(50),  
				@p_mhr_number_length		INT,
				@p_bay_no					VARCHAR(50),  
				@p_bay_no_length			INT,
				@p_mobile_park_name			VARCHAR(50),  
				@p_mobile_park_name_length INT,
				@p_park_folio_id			VARCHAR(50), 
				@p_park_folio_id_length		INT,
				@p_pid1						VARCHAR(50),  
				@p_pid2						VARCHAR(50),  
				@p_pid3						VARCHAR(50),  
				@p_pid4						VARCHAR(50),  
				@p_pid5						VARCHAR(50),   
				@p_pid_length				INT,
				@p_nts_block_num			VARCHAR(50),  
				@p_nts_block_num_length		INT,
				@p_nts_exception			VARCHAR(50),  
				@p_nts_exception_length		INT,
				@p_nts_map_num				VARCHAR(50),  
				@p_nts_map_num_length		INT,
				@p_nts_quarter_unit			VARCHAR(50),  
				@p_nts_quarter_unit_length	INT,
				@p_nts_unit					VARCHAR(50),  
				@p_nts_unit_length			INT,
				@p_project_num				VARCHAR(50),
				@p_proj_num_length			INT

	IF @p_Type = 'SIMPLE'
	BEGIN
		SELECT TOP 1
				@p_jurisdiction				= '324',  
				@p_parcel					= [A].[Parcel],  
				@p_parcel_length			= LEN([A].[Parcel]),
				@p_lot						= [A].[Lot],  
				@p_lot_length				= LEN([A].[Lot]),
				@p_strata_lot				= [A].[Strata_Lot_Number],  
				@p_strata_lot_length		= LEN([A].[Strata_Lot_Number]),
				@p_block					= [A].[Block_Number],  
				@p_block_length				= LEN([A].[Block_Number]),
				@p_sub_block				= [A].[Sub_Block],  
				@p_sub_block_length			= LEN([A].[Sub_Block]),  
				@p_plan						= [A].[Plan_Number],  
				@p_plan_length				= LEN([A].[Plan_Number]),  
				@p_sub_lot					= [A].[Suburban_Lot_Number],
				@p_sub_lot_length			= LEN([A].[Suburban_Lot_Number]),
				@p_part_1					= '??part_1 NOT FOUND??',
				@p_part_2					= '??part_2 NOT FOUND??',
				@p_part_3					= '??part_2 NOT FOUND??',
				@p_part_4					= '??part_4 NOT FOUND??',
				@p_part_length				= 100,
				@p_district_lot				= [A].[District_Lot],
				@p_district_lot_length		= LEN([A].[District_Lot]),
				@p_legal_subdivision		= '??legal_subdivision NOT FOUND??',  
				@p_legal_subdivision_length = 100,
				@p_section					= [A].[Section],  
				@p_section_length			= LEN([A].[Section]),  
				@p_township					= [A].[Township],  
				@p_township_length			= LEN([A].[Township]),  
				@p_range					= [A].[Range],  
				@p_range_length				= LEN([A].[Range]),  
				@p_meridian					= [A].[Meridian],  
				@p_meridian_length			= LEN([A].[Meridian]),  
				@p_bcaao_group				= [A].[BCA_AO_Group],  
				@p_bcaao_group_length		= LEN([A].[BCA_AO_Group]),
				@p_land_district			= [A].[Land_District],  
				@p_land_district_length		= LEN([A].[Land_District]),  
				@p_portion					= [A].[Portion],  
				@p_portion_length			= LEN([A].[Portion]),
				@p_except_plan				= [A].[Exception_Plan],  
				@p_except_plan_length		= LEN([A].[Exception_Plan]),
				@p_legal_text				= [A].[Legal_Text],  
				@p_legal_text_length		= LEN([A].[Legal_Text]),
				@p_air_space_parcel			= [A].[Air_Space_Parcel],  
				@p_air_space_parcel_length	= LEN([A].[Air_Space_Parcel]),
				@p_lease_licence_num		= [A].[Lease_Licence_Number],  
				@p_lease_licence_num_length = LEN([A].[Lease_Licence_Number]),
				@p_mf_num					= LEN('??mf_num NOT FOUND??'),  
				@p_mf_num_length			= 100,
				@p_mhr_number				= '??mhr_num NOT FOUND??',
				@p_mhr_number_length		= LEN('??mhr_num NOT FOUND??'),
				@p_bay_no					= '??bay_no NOT FOUND??',  
				@p_bay_no_length			= LEN('??bay_no NOT FOUND??'),
				@p_mobile_park_name			= '??mobile_park_name NOT FOUND??',
				@p_mobile_park_name_length	= LEN('??mobile_park_name NOT FOUND??'),
				@p_park_folio_id			= '??park_folio_id NOT FOUND??',
				@p_park_folio_id_length		= LEN('??park_folio_id NOT FOUND??'),
				@p_pid1						= [A].[Pid],  
				@p_pid2						= '',  
				@p_pid3						= '',  
				@p_pid4						= '',  
				@p_pid5						= '',   
				@p_pid_length				= LEN([A].[Pid]),
				@p_nts_block_num			= '??nts_block_num NOT FOUND??',
				@p_nts_block_num_length		= LEN('??nts_block_num NOT FOUND??'),
				@p_nts_exception			= '??nts_exception NOT FOUND??',
				@p_nts_exception_length		= LEN('??nts_exception NOT FOUND??'),
				@p_nts_map_num				= '??nts_map_num NOT FOUND??',
				@p_nts_map_num_length		= LEN('??nts_map_num NOT FOUND??'),
				@p_nts_quarter_unit			= [A].[NTS_Quarter],
				@p_nts_quarter_unit_length	= LEN([A].[NTS_Quarter]),
				@p_nts_unit					= [A].NTS_Unit,  
				@p_nts_unit_length			= LEN([A].NTS_Unit),
				@p_project_num				= [A].[OGC_Project_Number],
				@p_proj_num_length			= LEN([A].[OGC_Project_Number])
		FROM [dbo].[Parcel] AS [A]
	END

	SELECT [dbo].[FNC_FORMAT_LEGAL](	@p_jurisdiction				,  
										@p_parcel					,  
										@p_parcel_length			,
										@p_lot						,  
										@p_lot_length				,
										@p_strata_lot				,  
										@p_strata_lot_length		,
										@p_block					,  
										@p_block_length				,
										@p_sub_block				,  
										@p_sub_block_length			,
										@p_plan						,  
										@p_plan_length				,
										@p_sub_lot					,  
										@p_sub_lot_length			,
										@p_part_1					,
										@p_part_2					,
										@p_part_3					,  
										@p_part_4					,  
										@p_part_length				,
										@p_district_lot				,  
										@p_district_lot_length		,
										@p_legal_subdivision		,  
										@p_legal_subdivision_length ,
										@p_section					,  
										@p_section_length			,
										@p_township					,  
										@p_township_length			,
										@p_range					,  
										@p_range_length				,
										@p_meridian					,  
										@p_meridian_length			,
										@p_bcaao_group				,  
										@p_bcaao_group_length		,
										@p_land_district			,  
										@p_land_district_length		,
										@p_portion					,  
										@p_portion_length			,
										@p_except_plan				,  
										@p_except_plan_length		,
										@p_legal_text				,  
										@p_legal_text_length		,
										@p_air_space_parcel			,  
										@p_air_space_parcel_length	,
										@p_lease_licence_num		,  
										@p_lease_licence_num_length ,
										@p_mf_num					,  
										@p_mf_num_length			,
										@p_mhr_number				,  
										@p_mhr_number_length		,
										@p_bay_no					,  
										@p_bay_no_length			,
										@p_mobile_park_name			,  
										@p_mobile_park_name_length ,
										@p_park_folio_id			, 
										@p_park_folio_id_length		,
										@p_pid1						,  
										@p_pid2						,  
										@p_pid3						,  
										@p_pid4						,  
										@p_pid5						,   
										@p_pid_length				,
										@p_nts_block_num			,  
										@p_nts_block_num_length		,
										@p_nts_exception			,  
										@p_nts_exception_length		,
										@p_nts_map_num				,  
										@p_nts_map_num_length		,
										@p_nts_quarter_unit			,  
										@p_nts_quarter_unit_length	,
										@p_nts_unit					,  
										@p_nts_unit_length			,
										@p_project_num				,
										@p_proj_num_length			
									)
	IF @@ERROR <> 0
	BEGIN
		EXEC [dbo].[SP_LOG_ERROR](SELECT ERROR_MESSAGE(),ERROR_STATE(), ERROR_SEVERITY())
		RETURN NULL
	END

	RETURN 0
END
