CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'Regina123456#';
GO

CREATE CERTIFICATE GerryCertificate
WITH SUBJECT = 'EDW Protected Data';
GO

CREATE SYMMETRIC KEY GerrySymmetricKey
 WITH ALGORITHM = AES_128 
 ENCRYPTION BY CERTIFICATE GerryCertificate;
GO

