DBCC FREEPROCCACHE
GO
DBCC DROPCLEANBUFFERS
GO
  DECLARE @Type	VARCHAR(10)

SET @Type = 'SIMPLE'
--SET @Type = 'CO'
--SET @Type = 'ATTN'
--SET @Type = 'CO_ATTN'
--SET @Type = 'USA'
--SET @Type = 'FOREIGH'

EXEC dbo.SP_TEST_FORMAT_ONE_PID @Type